name: Auto deploy

on: push

jobs:
  pull-and-deploy-job:
    name: Pull from github and deploy
    runs-on: ["self-hosted", "linux", "x64"]
    steps:
      - name: pull-latest-code
        run: |
          cd ~/butfor-www/
          git pull

      - name: install-packages
        run: |
          cd ~/butfor-www/
          yarn install

      - name: build
        run: |
          cd ~/butfor-www/
          yarn build
